### ISSUE TITLE
WDS Connect Ticket Purchase not working

### ISSUE THREAD

**Issue by jeddc** [nickyhajal/world-domination-summit#100]
Two emails came in today with people not being able to buy Connect tickets. When clicking on purchase, the lightbox does the following:

<img width="1021" alt="connect-ticket-purchase-issue" src="https://cloud.githubusercontent.com/assets/11277509/15367744/3da9bd9a-1cdf-11e6-8363-b78b56f8bfa6.png">

**Comment by 193countries** [comment]
did this get resolved?

(p.s. not sure if replies to this email go to both of you, so i'm cc'ing
just in case)
