### ISSUE TITLE
Inability to add new attendees to manifest

### ISSUE THREAD

**Issue by jeddc** [nickyhajal/world-domination-summit#94]
I haven't been able to add new attendees to the manifest though it says "attendee added" when I go through the process. I search for them in the manifest and madmimi but cannot find them.

**Comment by nickyhajal** [comment]
Can you test this now? It seems to be working for me

**Comment by jeddc** [comment]
I've tried three times this evening and still can't seem to add someone to the manifest that also shows up in Madmimi
